language: csharp
solution: "./SimpleConsoleApp/SimpleConsoleApp.sln"
install:
- travis_retry nuget restore -source "https://www.nuget.org/api/v2" ./SimpleConsoleApp/SimpleConsoleApp.sln
script:
- xbuild ./SimpleConsoleApp/SimpleConsoleApp.sln
